### ISSUE TITLE
YX8018 product page link changed

### ISSUE THREAD

**Issue by gnbl** [mcauser/YX8018-solar-led-driver#1]
The product page link in https://github.com/mcauser/YX8018-solar-led-driver/blob/master/README.md points to YX8019.
The product page for YX8018 is currently http://shiningic.com/download.asp?id=7 
Current datasheet at http://shiningic.com/UpLoad/20130605111330984.pdf

**Comment by mcauser** [comment]
Right you are, thanks!
Fixed in 6454bdc70c9bc3a3ff6244a742c56e90e4ebabb7
